"""
ASOS A/B Testing Explorer
Interactive Streamlit app for exploring the ASOS Digital Experiments Dataset.
"""

import math
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
import seaborn as sns
import streamlit as st

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
DATA_PATH = BASE_DIR / "data" / "asos_digital_experiments_dataset.csv"
PLOTS_DIR = BASE_DIR / "outputs" / "plots"
SUMMARY_PATH = BASE_DIR / "outputs" / "experiment_summary.csv"

METRIC_LABELS = {1: "Metric 1", 2: "Metric 2", 3: "Metric 3", 4: "Metric 4"}

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="ASOS A/B Testing Explorer",
    page_icon="🧪",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

@st.cache_data
def load_raw():
    return pd.read_csv(DATA_PATH)


@st.cache_data
def load_summary():
    return pd.read_csv(SUMMARY_PATH)


def z_to_p(z: float) -> float:
    return 2 * (1 - 0.5 * (1 + math.erf(abs(z) / math.sqrt(2))))


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
st.sidebar.title("Navigation")
page = st.sidebar.radio(
    "Go to",
    [
        "Overview",
        "Experiment Deep-Dive",
        "Statistical Significance",
        "Saved Notebook Plots",
    ],
)

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
df = load_raw()
summary = load_summary()

# ===================================================================
# PAGE: Overview
# ===================================================================
if page == "Overview":
    st.title("ASOS A/B Testing Explorer")
    st.markdown(
        """
        This app explores the **ASOS Digital Experiments Dataset** -- a public
        dataset of online controlled experiments (A/B tests) run at ASOS
        between 2019 and 2020.

        Use the sidebar to navigate between sections:
        - **Overview** -- high-level dataset statistics.
        - **Experiment Deep-Dive** -- pick an experiment and watch control vs.
          treatment evolve over time.
        - **Statistical Significance** -- understand lift, z-scores, and
          p-values across all experiments.
        - **Saved Notebook Plots** -- the exact charts generated by the
          exploration notebook.
        """
    )

    st.subheader("Dataset at a glance")
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Experiments", df["experiment_id"].nunique())
    col2.metric("Metrics", df["metric_id"].nunique())
    col3.metric("Total rows", f"{len(df):,}")
    col4.metric("Variant IDs", ", ".join(str(v) for v in sorted(df["variant_id"].unique())))

    st.subheader("Experiment duration distribution")
    durations = df.groupby("experiment_id")["time_since_start"].max()
    fig, ax = plt.subplots(figsize=(8, 3.5))
    sns.histplot(durations, bins=30, kde=True, ax=ax, color="#4c78a8")
    ax.set_xlabel("Max time since start (hours)")
    ax.set_ylabel("Number of experiments")
    ax.set_title("How long do ASOS experiments run?")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("Sample rows")
    st.dataframe(df.head(20), use_container_width=True)

# ===================================================================
# PAGE: Experiment Deep-Dive
# ===================================================================
elif page == "Experiment Deep-Dive":
    st.title("Experiment Deep-Dive")
    st.markdown(
        "Pick an experiment and a metric, then watch control and treatment "
        "means evolve over the experiment's lifetime."
    )

    experiments = sorted(df["experiment_id"].unique())
    selected_exp = st.selectbox("Experiment", experiments)

    exp_df = df[df["experiment_id"] == selected_exp]
    available_metrics = sorted(exp_df["metric_id"].unique())
    selected_metric = st.selectbox(
        "Metric",
        available_metrics,
        format_func=lambda m: METRIC_LABELS.get(m, f"Metric {m}"),
    )

    exp_metric = (
        exp_df[exp_df["metric_id"] == selected_metric]
        .sort_values("time_since_start")
    )

    st.subheader("Control vs. Treatment over time")
    fig, ax = plt.subplots(figsize=(10, 5))
    for variant in sorted(exp_metric["variant_id"].unique()):
        vdf = exp_metric[exp_metric["variant_id"] == variant]
        ax.plot(vdf["time_since_start"], vdf["mean_c"], label=f"Var {variant} control", linestyle="--")
        ax.plot(vdf["time_since_start"], vdf["mean_t"], label=f"Var {variant} treatment", linestyle="-")
    ax.set_xlabel("Hours since experiment start")
    ax.set_ylabel("Metric value")
    ax.set_title(f"Experiment {selected_exp} · {METRIC_LABELS.get(selected_metric, f'Metric {selected_metric}')}")
    ax.legend(loc="best", fontsize="small")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("Final snapshot")
    final = exp_metric.groupby("variant_id").last().reset_index()
    final["lift"] = final["mean_t"] - final["mean_c"]
    st.dataframe(
        final[["variant_id", "count_c", "count_t", "mean_c", "mean_t", "lift"]].rename(
            columns={
                "variant_id": "Variant",
                "count_c": "N control",
                "count_t": "N treatment",
                "mean_c": "Mean control",
                "mean_t": "Mean treatment",
                "lift": "Lift (T - C)",
            }
        ),
        use_container_width=True,
    )

# ===================================================================
# PAGE: Statistical Significance
# ===================================================================
elif page == "Statistical Significance":
    st.title("Statistical Significance Across Experiments")
    st.markdown(
        """
        The summary below uses the **final time-point** for each
        experiment-metric-variant combination (excluding control-only rows).
        A two-sided z-test checks whether the treatment mean differs
        significantly from the control mean (alpha = 0.05).
        """
    )

    sig_count = summary["significant"].sum()
    total = len(summary)
    col1, col2, col3 = st.columns(3)
    col1.metric("Total comparisons", total)
    col2.metric("Significant (p < 0.05)", int(sig_count))
    col3.metric("Significant %", f"{100 * sig_count / total:.1f}%")

    st.subheader("Lift distribution")
    fig, ax = plt.subplots(figsize=(8, 4))
    sns.histplot(summary["lift"], bins=40, kde=True, ax=ax, color="#4c78a8")
    ax.axvline(0, color="gray", linewidth=0.8)
    ax.set_xlabel("Lift (treatment - control)")
    ax.set_ylabel("Count")
    ax.set_title("Distribution of observed lifts")
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("P-value distribution")
    fig, ax = plt.subplots(figsize=(8, 4))
    sns.histplot(summary["p_value"], bins=40, kde=False, ax=ax, color="#f58518")
    ax.axvline(0.05, color="red", linewidth=1, linestyle="--", label="alpha = 0.05")
    ax.set_xlabel("P-value")
    ax.set_ylabel("Count")
    ax.set_title("P-value distribution across all experiment-metric pairs")
    ax.legend()
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("Top lifts (absolute)")
    top = (
        summary.assign(abs_lift=lambda d: d["lift"].abs())
        .sort_values("abs_lift", ascending=False)
        .head(15)
    )
    fig, ax = plt.subplots(figsize=(10, 6))
    labels = top["experiment_id"] + " (m" + top["metric_id"].astype(str) + ")"
    colors = ["#f58518" if s else "#4c78a8" for s in top["significant"]]
    ax.barh(labels, top["lift"], color=colors)
    ax.axvline(0, color="gray", linewidth=0.8)
    ax.set_xlabel("Lift")
    ax.set_title("Top 15 absolute lifts (orange = significant)")
    ax.invert_yaxis()
    ax.xaxis.set_major_formatter(ticker.StrMethodFormatter("{x:.4f}"))
    fig.tight_layout()
    st.pyplot(fig)
    plt.close(fig)

    st.subheader("Full summary table")
    st.dataframe(
        summary[
            [
                "experiment_id",
                "metric_id",
                "variant_id",
                "count_control",
                "count_treatment",
                "mean_control",
                "mean_treatment",
                "lift",
                "relative_lift",
                "z_score",
                "p_value",
                "significant",
            ]
        ].sort_values("p_value"),
        use_container_width=True,
    )

# ===================================================================
# PAGE: Saved Notebook Plots
# ===================================================================
elif page == "Saved Notebook Plots":
    st.title("Saved Notebook Plots")
    st.markdown(
        "These are the exact figures generated by `notebooks/ab_testing_analysis.ipynb` "
        "and saved to `outputs/plots/`. They keep the Streamlit app in sync with the "
        "notebook analysis."
    )

    lift_bar = PLOTS_DIR / "metric_lift_bar.png"
    ts_plot = PLOTS_DIR / "time_series_selected_experiment.png"

    if lift_bar.exists():
        st.subheader("Metric lift bar chart")
        st.image(str(lift_bar), use_container_width=True)
    else:
        st.warning(f"Plot not found: {lift_bar}")

    if ts_plot.exists():
        st.subheader("Time-series for representative experiment")
        st.image(str(ts_plot), use_container_width=True)
    else:
        st.warning(f"Plot not found: {ts_plot}")
